/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package project;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author whath
 */
public class loading extends java.awt.Frame {

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loading = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        Loading.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.add(Loading);
        Loading.setBounds(130, 720, 1260, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sabg-removebg-preview.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(580, 310, 340, 210);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("SEASIDE HOTEL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(560, 500, 450, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("\"WIDE AND FREE JUST LIKE THE SEA\"");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 570, 210, 12);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("LOADING  . . . ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(690, 690, 100, 20);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/976239.jpg"))); // NOI18N
        back.setText("jLabel1");
        jPanel1.add(back);
        back.setBounds(0, 0, 2043, 1336);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       loading load = new loading();
load.setVisible(true);

        try{
for(int i=0;i<100;i++){
    Thread.sleep(60);
    load.Loading.setValue(i);
}
        
    }   catch (InterruptedException ex) {
            Logger.getLogger(loading.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        load.dispose();
       login login = new login();
        login.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loading;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
