package project;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainTain extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;
 
    public MainTain() {
        initComponents();
        
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/userregistration","root","");
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        fillListView();
        
        //set controls to disable by default
        
        //txtStudentNumber.disable();
        txtLastName.disable();
        txtFirstName.disable();
        txtMiddleName.disable();
    //    cboCourse.disable();
        txtBday.disable();
        txtAge.disable();
        txtContactNumber.disable();
        /*
        txtEmailAddress.disable();
        txtAddress.disable();
        txtStatus.disable();
        txtNationality.disable();
        txtZodiac.disable();
        txtSex.disable();
        txtReligion.disable();
        txtYearLevel.disable();
        txtSection.disable();
        txtPronouns.disable();
        txtBloodType.disable();
        txtGuardian.disable();
        */
        //set button to default on and off
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnClear.setEnabled(false);
        btnCancel.setEnabled(true);
        btnCancel.setText("Close");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        cboCourse = new javax.swing.JComboBox<>();
        txtBday = new javax.swing.JFormattedTextField();
        txtContactNumber = new javax.swing.JFormattedTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListOfStudents = new javax.swing.JTable();
        txtStudentNumber = new javax.swing.JFormattedTextField();
        btnOpen = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtZodiac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtReligion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtYearLevel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPronouns = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtBloodType = new javax.swing.JTextField();
        txtGuardian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information Form");
        setSize(new java.awt.Dimension(1366, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Information Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Student Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Middle Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Birthday:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Contact Number:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Email Address:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Age:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Course:");

        cboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Bachelor of Science in Information Technology", "Bachelor of Science in Computer Engineering", "Bachelor of Science in Data Science", "Bachelor of Science in Computer Science", "Bachelor of Science in Information Systems", "Bachelor of Science in Enterntainment and Multimedia Computing", "Bachelor of Multimedia Arts" }));

        txtBday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtBday.setText("mm/dd/yyyy");
        txtBday.setToolTipText("");

        try {
            txtContactNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+63)###-####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Address:");

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });

        tblListOfStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Number", "Last Name", "First Name", "Middle Name", "Course", "Birthday", "Age", "Contact Number", "Email Address", "Address", "Status", "Nationality", "Zodiac", "Sex", "Religion", "Year Level", "Section", "Pronouns", "Bloodtype", "Guardian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListOfStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListOfStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListOfStudents);

        try {
            txtStudentNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtStudentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNumberActionPerformed(evt);
            }
        });

        btnOpen.setText("Open New Form");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Status");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Nationality");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Zodiac");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Sex");

        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Religion");

        txtReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReligionActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Year Level");

        txtYearLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearLevelActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Section");

        txtSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSectionActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Pronouns");

        txtPronouns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPronounsActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Bloodtype");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Guardian");

        txtBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodTypeActionPerformed(evt);
            }
        });

        txtGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStudentNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPronouns, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(26, 26, 26)
                            .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(26, 26, 26)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(26, 26, 26)
                            .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(26, 26, 26)
                            .addComponent(txtYearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpen)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtPronouns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpen)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
        cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
        txtContactNumber.setText("");
        txtEmailAddress.setText("");
        txtAddress.setText("");
        txtStatus.setText("");
        txtNationality.setText("");
        txtZodiac.setText("");
        txtSex.setText("");
        txtReligion.setText("");
        txtYearLevel.setText("");
        txtSection.setText("");
        txtPronouns.setText("");
        txtBloodType.setText("");
        txtGuardian.setText("");
        

        txtStudentNumber.setEnabled(true);
        txtStudentNumber.setBackground(Color.white);
        txtLastName.setEnabled(true);
        txtLastName.setBackground(Color.white);
        txtFirstName.setEnabled(true);
        txtFirstName.setBackground(Color.white);
        txtMiddleName.setEnabled(true);
        txtMiddleName.setBackground(Color.white);
        cboCourse.setEnabled(true);
        cboCourse.setBackground(Color.white);
        txtBday.setEnabled(true);
        txtBday.setBackground(Color.white);
        txtAge.setEnabled(true);
        txtAge.setBackground(Color.white);
        txtContactNumber.setEnabled(true);
        txtContactNumber.setBackground(Color.white);
        txtEmailAddress.setEnabled(true);
        txtEmailAddress.setBackground(Color.white);
        txtAddress.setEnabled(true);
        txtAddress.setBackground(Color.white);
        txtStatus.setEnabled(true);
        txtStatus.setBackground(Color.white);
        txtNationality.setEnabled(true);
        txtNationality.setBackground(Color.white);
        txtZodiac.setEnabled(true);
        txtZodiac.setBackground(Color.white);
        txtSex.setEnabled(true);
        txtSex.setBackground(Color.white);
        txtReligion.setEnabled(true);
        txtReligion.setBackground(Color.white);
        txtYearLevel.setEnabled(true);
        txtYearLevel.setBackground(Color.white);
        txtSection.setEnabled(true);
        txtSection.setBackground(Color.white);
        txtPronouns.setEnabled(true);
        txtPronouns.setBackground(Color.white);
        txtBloodType.setEnabled(true);
        txtBloodType.setBackground(Color.white);
        txtGuardian.setEnabled(true);
        txtGuardian.setBackground(Color.white);
        
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        btnClear.setEnabled(true);
        btnCancel.setEnabled(true);
        btnCancel.setText("Cancel");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        btnClear.setEnabled(true);
        btnCancel.setEnabled(true);
        btnCancel.setText("Cancel");
        btnSave.setText("Update");
        
        txtStudentNumber.setEnabled(false);
        txtStudentNumber.setBackground(Color.white);
        txtLastName.setEnabled(true);
        txtLastName.setBackground(Color.white);
        txtFirstName.setEnabled(true);
        txtFirstName.setBackground(Color.white);
        txtMiddleName.setEnabled(true);
        txtMiddleName.setBackground(Color.white);
        cboCourse.setEnabled(true);
        cboCourse.setBackground(Color.white);
        txtBday.setEnabled(true);
        txtBday.setBackground(Color.white);
        txtAge.setEnabled(true);
        txtAge.setBackground(Color.white);
        txtContactNumber.setEnabled(true);
        txtContactNumber.setBackground(Color.white);
        txtEmailAddress.setEnabled(true);
        txtEmailAddress.setBackground(Color.white);
        txtAddress.setEnabled(true);
        txtAddress.setBackground(Color.white);
        txtStatus.setEnabled(true);
        txtStatus.setBackground(Color.white);
        txtNationality.setEnabled(true);
        txtNationality.setBackground(Color.white);
        txtZodiac.setEnabled(true);
        txtZodiac.setBackground(Color.white);
        txtSex.setEnabled(true);
        txtSex.setBackground(Color.white);
        txtReligion.setEnabled(true);
        txtReligion.setBackground(Color.white);
        txtYearLevel.setEnabled(true);
        txtYearLevel.setBackground(Color.white);
        txtSection.setEnabled(true);
        txtSection.setBackground(Color.white);
        txtPronouns.setEnabled(true);
        txtPronouns.setBackground(Color.white);
        txtBloodType.setEnabled(true);
        txtBloodType.setBackground(Color.white);
        txtGuardian.setEnabled(true);
        txtGuardian.setBackground(Color.white);

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String studentNumber = txtStudentNumber.getText();
        
        
            int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete the selected record?", "DELETE RECORD",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                
                try{
                    String  query = "DELETE FROM `studenttbl` WHERE `studentNumber` = '"+studentNumber+"'";
                    statement = con.prepareStatement(query);
                    statement.execute();
                    
                    JOptionPane.showMessageDialog(this, "Message has been successfully deleted!","INFORMATION", JOptionPane.OK_OPTION);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error in deleting... "+e);
                }
            
                }else if (result == JOptionPane.NO_OPTION){
                   
                }

    
        fillListView();
        
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
        cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
        txtContactNumber.setText("");
        txtEmailAddress.setText("");
        txtAddress.setText("");
        txtStatus.setText("");
        txtNationality.setText("");
        txtZodiac.setText("");
        txtSex.setText("");
        txtReligion.setText("");
        txtYearLevel.setText("");
        txtSection.setText("");
        txtPronouns.setText("");
        txtBloodType.setText("");
        txtGuardian.setText("");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
        cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
        txtContactNumber.setText("");
        txtEmailAddress.setText("");
        txtAddress.setText("");
        txtStatus.setText("");
        txtNationality.setText("");
        txtZodiac.setText("");
        txtSex.setText("");
        txtReligion.setText("");
        txtYearLevel.setText("");
        txtSection.setText("");
        txtPronouns.setText("");
        txtBloodType.setText("");
        txtGuardian.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    if(btnSave.getText().equals("Save"))
    {
        if(txtStudentNumber.getText().isEmpty() || txtLastName.getText().isEmpty() || txtFirstName.getText().isEmpty() || txtMiddleName.getText().isEmpty() || cboCourse.equals(" ") || txtBday.getText().isEmpty() || txtAge.getText().isEmpty() || txtContactNumber.getText().isEmpty() || txtEmailAddress.getText().isEmpty() || txtAddress.getText().isEmpty() || txtStatus.getText().isEmpty() || txtNationality.getText().isEmpty() || txtZodiac.getText().isEmpty()
            || txtSex.getText().isEmpty() || txtReligion.getText().isEmpty() || txtYearLevel.getText().isEmpty()
             || txtSection.getText().isEmpty() || txtPronouns.getText().isEmpty() || txtBloodType.getText().isEmpty()
              || txtGuardian.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete all fields with correct entries!",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String studentNumber;
            String lastName;
            String firstName;
            String middleName;
            String course;
            String bday;
            String age;
            String contactNumber;
            String emailAddress;
            String address;
            String Status;
            String Nationality;
            String Zodiac;
            String Sex;
            String Religion;
            String YearLevel;
            String Section;
            String Pronouns;
            String BloodType;
            String Guardian;
            
        
            studentNumber = txtStudentNumber.getText();
            lastName = txtLastName.getText();
            firstName = txtFirstName.getText();
            middleName = txtMiddleName.getText();
            course = cboCourse.getSelectedItem().toString();
            bday = txtBday.getText();
            age = txtAge.getText();
            contactNumber = txtContactNumber.getText();
            emailAddress = txtEmailAddress.getText();
            address = txtAddress.getText();
            Status = txtStatus.getText();
            Nationality = txtNationality.getText();
            Zodiac = txtZodiac.getText();
            Sex = txtSex.getText();
            Religion = txtReligion.getText();
            YearLevel = txtYearLevel.getText();
            Section = txtSection.getText();
            Pronouns = txtPronouns.getText();
            BloodType = txtBloodType.getText();
            Guardian = txtGuardian.getText();


            try{
                //String query = "INSERT INTO `demo_table`(`Username`, `Password`) VALUES ('"+Username+"','"+Password+"')";
                String  query = "INSERT INTO `studenttbl`(`studentNumber`, `lastName`, `firstName`, `middleName`, `age`, `address`, `contactNumber`, `emailAddress`, `birthday`, `course`, `Status`, `Nationality`, `Zodiac`, `Sex`, `Religion`, `YearLevel`, `Section`, `Pronouns`, `BloodType`, `Guardian`) " + "VALUES ('"+studentNumber+"','"+lastName+"','"+firstName+"','"+middleName+"','"+age+"','"+address+"','"+contactNumber+"','"+emailAddress+"','"+bday+"','"+course+"','"+Status+"','"+Nationality+"','"+Zodiac+"','"+Sex+"','"+Religion+"','"+YearLevel+"','"+Section+"','"+Pronouns+"','"+BloodType+"','"+Guardian+"')";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Student Record Has Been Successfully Saved!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                
                fillListView();
                        
                txtStudentNumber.setText("");
                txtLastName.setText("");
                txtFirstName.setText("");
                txtMiddleName.setText("");
                cboCourse.setSelectedItem(" ");
                txtBday.setText("");
                txtAge.setText("");
                txtContactNumber.setText("");
                txtEmailAddress.setText("");
                txtAddress.setText("");
                txtStatus.setText("");
                txtNationality.setText("");
                txtZodiac.setText("");
                txtSex.setText("");
                txtReligion.setText("");
                txtYearLevel.setText("");
                txtSection.setText("");
                txtPronouns.setText("");
                txtBloodType.setText("");
                txtGuardian.setText("");
                
                
                txtStudentNumber.setEnabled(false);
                txtLastName.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtMiddleName.setEnabled(false);
                cboCourse.setEnabled(false);
                txtBday.setEnabled(false);
                txtBday.setText("mm/dd/yyyy");
                txtAge.setEnabled(false);
                txtContactNumber.setEnabled(false);
                txtEmailAddress.setEnabled(false);
                txtAddress.setEnabled(false);
                txtStatus.setEnabled(false);
                txtNationality.setEnabled(false);
                txtZodiac.setEnabled(false);
                txtSex.setEnabled(false);
                txtReligion.setEnabled(false);
                txtYearLevel.setEnabled(false);
                txtSection.setEnabled(false);
                txtPronouns.setEnabled(false);
                txtBloodType.setEnabled(false);
                txtGuardian.setEnabled(false);
                
                //set button to default on and off
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                btnSave.setEnabled(false);
                btnClear.setEnabled(false);
                btnCancel.setEnabled(true);
                btnCancel.setText("Close");
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    else 
    {
        //dito yung update
        if(txtStudentNumber.getText().isEmpty() || txtLastName.getText().isEmpty() || txtFirstName.getText().isEmpty() || txtMiddleName.getText().isEmpty() || cboCourse.equals(" ") || txtBday.getText().isEmpty() || txtAge.getText().isEmpty() || txtContactNumber.getText().isEmpty() || txtEmailAddress.getText().isEmpty() || txtAddress.getText().isEmpty() || txtStatus.getText().isEmpty() || txtNationality.getText().isEmpty() || txtZodiac.getText().isEmpty()
            || txtSex.getText().isEmpty() || txtReligion.getText().isEmpty() || txtYearLevel.getText().isEmpty()
             || txtSection.getText().isEmpty() || txtPronouns.getText().isEmpty() || txtBloodType.getText().isEmpty()
              || txtGuardian.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete all fields with correct entries!",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String studentNumber;
            String lastName;
            String firstName;
            String middleName;
            String course;
            String bday;
            String age;
            String contactNumber;
            String emailAddress;
            String address;
            String Status;
            String Nationality;
            String Zodiac;
            String Sex;
            String Religion;
            String YearLevel;
            String Section;
            String Pronouns;
            String BloodType;
            String Guardian;
        
            studentNumber = txtStudentNumber.getText();
            lastName = txtLastName.getText();
            firstName = txtFirstName.getText();
            middleName = txtMiddleName.getText();
            course = cboCourse.getSelectedItem().toString();
            bday = txtBday.getText();
            age = txtAge.getText();
            contactNumber = txtContactNumber.getText();
            emailAddress = txtEmailAddress.getText();
            address = txtAddress.getText();
            Status = txtStatus.getText();
            Nationality = txtNationality.getText();
            Zodiac = txtZodiac.getText();
            Sex = txtSex.getText();
            Religion = txtReligion.getText();
            YearLevel = txtYearLevel.getText();
            Section = txtSection.getText();
            Pronouns = txtPronouns.getText();
            BloodType = txtBloodType.getText();
            Guardian = txtGuardian.getText();
            
            
            
            try{
                //String query = "INSERT INTO `demo_table`(`Username`, `Password`) VALUES ('"+Username+"','"+Password+"')";
                //String  query = "INSERT INTO `studenttbl`(`studentNumber`, `lastName`, `firstName`, `middleName`, `age`, `address`, `contactNumber`, `emailAddress`, `birthday`, `course`) VALUES ('"+studentNumber+"','"+lastName+"','"+firstName+"','"+middleName+"','"+age+"','"+address+"','"+contactNumber+"','"+emailAddress+"','"+bday+"','"+course+"')";
                String query = "UPDATE `studenttbl` SET `lastName`='"+lastName+"',`firstName`='"+firstName+"',`middleName`='"+middleName+"',`age`='"+age+"',`address`='"+address+"',`contactNumber`='"+contactNumber+"',`emailAddress`='"+emailAddress+"',`birthday`='"+bday+"',`course`='"+course+",`Status`='"+Status+"',`Nationality`='"+Nationality+"',`Zodiac`='"+Zodiac+"',`Sex`='"+Sex+"',`Religion`='"+Religion+"',`YearLevel`='"+YearLevel+"',`Section`='"+Section+"',`Pronouns`='"+Pronouns+"',`BloodType`='"+BloodType+"',`Guardian`='"+Guardian+"'' WHERE studentNumber = '"+studentNumber+"'";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Student Record Has Been Successfully Saved!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                
                fillListView();
                        
                txtStudentNumber.setText("");
                txtLastName.setText("");
                txtFirstName.setText("");
                txtMiddleName.setText("");
                cboCourse.setSelectedItem(" ");
                txtBday.setText("");
                txtAge.setText("");
                txtContactNumber.setText("");
                txtEmailAddress.setText("");
                txtAddress.setText("");
                txtStatus.setText("");
                txtNationality.setText("");
                txtZodiac.setText("");
                txtSex.setText("");
                txtReligion.setText("");
                txtYearLevel.setText("");
                txtSection.setText("");
                txtPronouns.setText("");
                txtBloodType.setText("");
                txtGuardian.setText("");
                
                txtStudentNumber.setEnabled(false);
                txtLastName.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtMiddleName.setEnabled(false);
                cboCourse.setEnabled(false);
                txtBday.setEnabled(false);
                txtBday.setText("mm/dd/yyyy");
                txtAge.setEnabled(false);
                txtContactNumber.setEnabled(false);
                txtEmailAddress.setEnabled(false);
                txtAddress.setEnabled(false);
                txtStatus.setEnabled(false);
                txtNationality.setEnabled(false);
                txtZodiac.setEnabled(false);
                txtSex.setEnabled(false);
                txtReligion.setEnabled(false);
                txtYearLevel.setEnabled(false);
                txtSection.setEnabled(false);
                txtPronouns.setEnabled(false);
                txtBloodType.setEnabled(false);
                txtGuardian.setEnabled(false);
                
                //set button to default on and off
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                btnSave.setEnabled(false);
                btnClear.setEnabled(false);
                btnCancel.setEnabled(true);
                btnCancel.setText("Close");
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
        }
        
    }
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (btnCancel.getText().equals("Close"))
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblListOfStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListOfStudentsMouseClicked
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnClear.setEnabled(false);
        btnCancel.setEnabled(true);
        btnCancel.setText("Close");
                
        String studentNumber;
        String lastName;
        String firstName;
        String middleName;
        String course;
        String bday;
        String age;
        String contactNumber;
        String emailAddress;
        String address;
        String Status;
        String Nationality;
        String Zodiac;
        String Sex;
        String Religion;
        String YearLevel;
        String Section;
        String Pronouns;
        String BloodType;
        String Guardian;
        
        int row = tblListOfStudents.getSelectedRow();
        
        studentNumber = (tblListOfStudents.getModel().getValueAt(row,0).toString());
        lastName = (tblListOfStudents.getModel().getValueAt(row,1).toString());
        firstName = (tblListOfStudents.getModel().getValueAt(row,2).toString());
        middleName = (tblListOfStudents.getModel().getValueAt(row,3).toString());
        course = (tblListOfStudents.getModel().getValueAt(row,4).toString());
        bday = (tblListOfStudents.getModel().getValueAt(row,5).toString());
        age = (tblListOfStudents.getModel().getValueAt(row,6).toString());
        contactNumber = (tblListOfStudents.getModel().getValueAt(row,7).toString());
        emailAddress = (tblListOfStudents.getModel().getValueAt(row,8).toString());
        address = (tblListOfStudents.getModel().getValueAt(row,9).toString());
        Status = (tblListOfStudents.getModel().getValueAt(row,10).toString());
        Nationality = (tblListOfStudents.getModel().getValueAt(row,11).toString());
        Zodiac = (tblListOfStudents.getModel().getValueAt(row,12).toString());
        Sex = (tblListOfStudents.getModel().getValueAt(row,13).toString());
        Religion = (tblListOfStudents.getModel().getValueAt(row,14).toString());
        YearLevel = (tblListOfStudents.getModel().getValueAt(row,15).toString());
        Section = (tblListOfStudents.getModel().getValueAt(row,16).toString());
        Pronouns = (tblListOfStudents.getModel().getValueAt(row,17).toString());
        BloodType = (tblListOfStudents.getModel().getValueAt(row,18).toString());
        Guardian = (tblListOfStudents.getModel().getValueAt(row,19).toString());
        
        txtStudentNumber.setText(studentNumber);
        txtLastName.setText(lastName);
        txtFirstName.setText(firstName);
        txtMiddleName.setText(middleName);
        cboCourse.setSelectedItem(course);
        txtBday.setText(bday);
        txtAge.setText(age);
        txtContactNumber.setText(contactNumber);
        txtEmailAddress.setText(emailAddress);
        txtAddress.setText(address);
        txtStatus.setText(Status);
        txtNationality.setText(Nationality);
        txtZodiac.setText(Zodiac);
        txtSex.setText(Sex);
        txtReligion.setText(Religion);
        txtYearLevel.setText(YearLevel);
        txtSection.setText(Section);
        txtPronouns.setText(Pronouns);
        txtBloodType.setText(BloodType);
        txtGuardian.setText(Guardian);
        
    }//GEN-LAST:event_tblListOfStudentsMouseClicked

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
    
    }//GEN-LAST:event_btnOpenActionPerformed

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    private void txtYearLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearLevelActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectionActionPerformed

    private void txtPronounsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPronounsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPronounsActionPerformed

    private void txtBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodTypeActionPerformed

    private void txtGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtStudentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListOfStudents;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JFormattedTextField txtBday;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JFormattedTextField txtContactNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGuardian;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPronouns;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JFormattedTextField txtStudentNumber;
    private javax.swing.JTextField txtYearLevel;
    private javax.swing.JTextField txtZodiac;
    // End of variables declaration//GEN-END:variables

    private void fillListView() {
        try{

            String  query = "SELECT * FROM `studenttbl`";
            statement = con.prepareStatement(query);
            result = statement.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)tblListOfStudents.getModel();
            tm.setRowCount(0);

            while(result.next()){
                Object o[] = {result.getString("studentNumber"),result.getString("lastName"),result.getString("firstName"),result.getString("middleName"),result.getString("course"),result.getString("birthday"),result.getString("age"),result.getString("contactNumber"),result.getString("emailAddress"),result.getString("address"),result.getString("Status"),result.getString("Nationality"),result.getString("Zodiac"),result.getString("Sex"),result.getString("Religion"),result.getString("YearLevel"),result.getString("Section"),result.getString("Pronouns"),result.getString("BloodType"),result.getString("Guardian")};
                tm.addRow(o);
                }
            }
            catch(Exception e){

                JOptionPane.showMessageDialog(null,"Error in Employee Grid View..... "+e);
            }
    }
}