package project;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StudentInformationForm extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement statement = null;
    ResultSet result = null;
    
    public StudentInformationForm() {
        initComponents();
        
        try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/userregistration","root","");
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        fillListView();
        
        //set controls to disable by default
        
        txtStudentNumber.disable();
        txtLastName.disable();
        txtFirstName.disable();
        txtMiddleName.disable();
      //  cboCourse.disable();
        txtBday.disable();
        txtAge.disable();
        //txtContactNumber.disable();
        txtEmailAddress.disable();
      //  txtAddress.disable();
        
        
        //set button to default on and off
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnClear.setEnabled(false);
        btnCancel.setEnabled(true);
        btnCancel.setText("Close");
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtBday = new javax.swing.JFormattedTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtEmailAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListOfStudents = new javax.swing.JTable();
        txtStudentNumber = new javax.swing.JFormattedTextField();
        btnOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information Form");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Student Information Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Student Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Middle Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Birthday:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Email Address:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Age:");

        txtBday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtBday.setText("mm/dd/yyyy");
        txtBday.setToolTipText("");

        btnAdd.setText("Add New");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblListOfStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Number", "Last Name", "First Name", "Middle Name", "Course", "Birthday", "Age", "Contact Number", "Email Address", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListOfStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListOfStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListOfStudents);

        try {
            txtStudentNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnOpen.setText("Open New Form");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLastName)
                                                .addComponent(txtFirstName)
                                                .addComponent(txtMiddleName)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)))))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(821, 821, 821)
                        .addComponent(btnOpen))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel2))
                                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdd)
                                    .addComponent(btnEdit)
                                    .addComponent(btnDelete))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCancel)
                                    .addComponent(btnSave)
                                    .addComponent(btnClear))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
     //   cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
      //  txtContactNumber.setText("");
        txtEmailAddress.setText("");
       // txtAddress.setText("");
        
        txtStudentNumber.setEnabled(true);
        txtStudentNumber.setBackground(Color.white);
        txtLastName.setEnabled(true);
        txtLastName.setBackground(Color.white);
        txtFirstName.setEnabled(true);
        txtFirstName.setBackground(Color.white);
        txtMiddleName.setEnabled(true);
        txtMiddleName.setBackground(Color.white);
      //  cboCourse.setEnabled(true);
      ///  cboCourse.setBackground(Color.white);
        txtBday.setEnabled(true);
        txtBday.setBackground(Color.white);
        txtAge.setEnabled(true);
        txtAge.setBackground(Color.white);
       // txtContactNumber.setEnabled(true);
      //  txtContactNumber.setBackground(Color.white);
        txtEmailAddress.setEnabled(true);
        txtEmailAddress.setBackground(Color.white);
      //  txtAddress.setEnabled(true);
       // txtAddress.setBackground(Color.white);
        
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        btnClear.setEnabled(true);
        btnCancel.setEnabled(true);
        btnCancel.setText("Cancel");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        btnClear.setEnabled(true);
        btnCancel.setEnabled(true);
        btnCancel.setText("Cancel");
        btnSave.setText("Update");
        
        txtStudentNumber.setEnabled(false);
        txtStudentNumber.setBackground(Color.white);
        txtLastName.setEnabled(true);
        txtLastName.setBackground(Color.white);
        txtFirstName.setEnabled(true);
        txtFirstName.setBackground(Color.white);
        txtMiddleName.setEnabled(true);
        txtMiddleName.setBackground(Color.white);
       // cboCourse.setEnabled(true);
       // cboCourse.setBackground(Color.white);
        txtBday.setEnabled(true);
        txtBday.setBackground(Color.white);
        txtAge.setEnabled(true);
        txtAge.setBackground(Color.white);
       // txtContactNumber.setEnabled(true);
       // txtContactNumber.setBackground(Color.white);
        txtEmailAddress.setEnabled(true);
        txtEmailAddress.setBackground(Color.white);
      //  txtAddress.setEnabled(true);
       // txtAddress.setBackground(Color.white);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String studentNumber = txtStudentNumber.getText();
        
        
            int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete the selected record?", "DELETE RECORD",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(result == JOptionPane.YES_OPTION){
                
                try{
                    String  query = "DELETE FROM `studenttbl` WHERE `studentNumber` = '"+studentNumber+"'";
                    statement = con.prepareStatement(query);
                    statement.execute();
                    
                    JOptionPane.showMessageDialog(this, "Message has been successfully deleted!","INFORMATION", JOptionPane.OK_OPTION);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error in deleting... "+e);
                }
            
                }else if (result == JOptionPane.NO_OPTION){
                   
                }

    
        fillListView();
        
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
      //  cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
       // txtContactNumber.setText("");
        txtEmailAddress.setText("");
       // txtAddress.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtStudentNumber.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
       // cboCourse.setSelectedItem(" ");
        txtBday.setText("");
        txtAge.setText("");
       // txtContactNumber.setText("");
        txtEmailAddress.setText("");
       // txtAddress.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    if(btnSave.getText().equals("Save"))
    {
        if(txtStudentNumber.getText().isEmpty() || txtLastName.getText().isEmpty() || txtFirstName.getText().isEmpty() || txtMiddleName.getText().isEmpty()  || txtBday.getText().isEmpty() || txtAge.getText().isEmpty() || txtEmailAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete all fields with correct entries!",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String studentNumber;
            String lastName;
            String firstName;
            String middleName;
            String course;
            String bday;
            String age;
            String contactNumber;
            String emailAddress;
            String address;
        
            studentNumber = txtStudentNumber.getText();
            lastName = txtLastName.getText();
            firstName = txtFirstName.getText();
            middleName = txtMiddleName.getText();
          //  course = cboCourse.getSelectedItem().toString();
            bday = txtBday.getText();
            age = txtAge.getText();
          //  contactNumber = txtContactNumber.getText();
         //   emailAddress = txtEmailAddress.getText();
          //  address = txtAddress.getText();
            
            try{
                //String query = "INSERT INTO `demo_table`(`Username`, `Password`) VALUES ('"+Username+"','"+Password+"')";
                String  query = "INSERT INTO `studenttbl`(`studentNumber`, `lastName`, `firstName`, `middleName`, `age`, `address`, `contactNumber`, `emailAddress`, `birthday`, `course`) VALUES ('"+studentNumber+"','"+lastName+"','"+firstName+"','"+middleName+"','"+age+"','"+bday+"')";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Student Record Has Been Successfully Saved!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                
                fillListView();
                        
                txtStudentNumber.setText("");
                txtLastName.setText("");
                txtFirstName.setText("");
                txtMiddleName.setText("");
            //    cboCourse.setSelectedItem(" ");
                txtBday.setText("");
                txtAge.setText("");
               // txtContactNumber.setText("");
                txtEmailAddress.setText("");
              //  txtAddress.setText("");
                
                txtStudentNumber.setEnabled(false);
                txtLastName.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtMiddleName.setEnabled(false);
              //  cboCourse.setEnabled(false);
                txtBday.setEnabled(false);
                txtBday.setText("mm/dd/yyyy");
                txtAge.setEnabled(false);
              //  txtContactNumber.setEnabled(false);
                txtEmailAddress.setEnabled(false);
              //  txtAddress.setEnabled(false);
                
                //set button to default on and off
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                btnSave.setEnabled(false);
                btnClear.setEnabled(false);
                btnCancel.setEnabled(true);
                btnCancel.setText("Close");
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    else 
    {
        //dito yung update
        if(txtStudentNumber.getText().isEmpty() || txtLastName.getText().isEmpty() || txtFirstName.getText().isEmpty() || txtMiddleName.getText().isEmpty() || txtBday.getText().isEmpty() || txtAge.getText().isEmpty() ||  txtEmailAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete all fields with correct entries!",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String studentNumber;
            String lastName;
            String firstName;
            String middleName;
            String course;
            String bday;
            String age;
            String contactNumber;
            String emailAddress;
            String address;
        
            studentNumber = txtStudentNumber.getText();
            lastName = txtLastName.getText();
            firstName = txtFirstName.getText();
            middleName = txtMiddleName.getText();
           // course = cboCourse.getSelectedItem().toString();
            bday = txtBday.getText();
            age = txtAge.getText();
            //contactNumber = txtContactNumber.getText();
            emailAddress = txtEmailAddress.getText();
           // address = txtAddress.getText();
            
            studentNumber = txtStudentNumber.getText();
            lastName = txtLastName.getText();
            firstName = txtFirstName.getText();
            middleName = txtMiddleName.getText();
          //  course = cboCourse.getSelectedItem().toString();
            bday = txtBday.getText();
            age = txtAge.getText();
           // contactNumber = txtContactNumber.getText();
            emailAddress = txtEmailAddress.getText();
           // address = txtAddress.getText();
            
            try{
                //String query = "INSERT INTO `demo_table`(`Username`, `Password`) VALUES ('"+Username+"','"+Password+"')";
                //String  query = "INSERT INTO `studenttbl`(`studentNumber`, `lastName`, `firstName`, `middleName`, `age`, `address`, `contactNumber`, `emailAddress`, `birthday`, `course`) VALUES ('"+studentNumber+"','"+lastName+"','"+firstName+"','"+middleName+"','"+age+"','"+address+"','"+contactNumber+"','"+emailAddress+"','"+bday+"','"+course+"')";
                String query = "UPDATE `studenttbl` SET `lastName`='"+lastName+"',`firstName`='"+firstName+"',`middleName`='"+middleName+"',`age`='"+age+"',`emailAddress`='"+emailAddress+"',`birthday`='"+bday+"' WHERE studentNumber = '"+studentNumber+"'";
                statement = con.prepareStatement(query);
                statement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Student Record Has Been Successfully Saved!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                
                fillListView();
                        
                txtStudentNumber.setText("");
                txtLastName.setText("");
                txtFirstName.setText("");
                txtMiddleName.setText("");
              //  cboCourse.setSelectedItem(" ");
                txtBday.setText("");
                txtAge.setText("");
               // txtContactNumber.setText("");
                txtEmailAddress.setText("");
            //   txtAddress.setText("");
                
                txtStudentNumber.setEnabled(false);
                txtLastName.setEnabled(false);
                txtFirstName.setEnabled(false);
                txtMiddleName.setEnabled(false);
              //  cboCourse.setEnabled(false);
                txtBday.setEnabled(false);
                txtBday.setText("mm/dd/yyyy");
                txtAge.setEnabled(false);
               // txtContactNumber.setEnabled(false);
                txtEmailAddress.setEnabled(false);
               // txtAddress.setEnabled(false);
                
                //set button to default on and off
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(false);
                btnDelete.setEnabled(false);
                btnSave.setEnabled(false);
                btnClear.setEnabled(false);
                btnCancel.setEnabled(true);
                btnCancel.setText("Close");
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
        }
        
    }
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (btnCancel.getText().equals("Close"))
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblListOfStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListOfStudentsMouseClicked
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnClear.setEnabled(false);
        btnCancel.setEnabled(true);
        btnCancel.setText("Close");
                
        String studentNumber;
        String lastName;
        String firstName;
        String middleName;
        String course;
        String bday;
        String age;
        String contactNumber;
        String emailAddress;
        String address;
        
        int row = tblListOfStudents.getSelectedRow();
        
        studentNumber = (tblListOfStudents.getModel().getValueAt(row,0).toString());
        lastName = (tblListOfStudents.getModel().getValueAt(row,1).toString());
        firstName = (tblListOfStudents.getModel().getValueAt(row,2).toString());
        middleName = (tblListOfStudents.getModel().getValueAt(row,3).toString());
        course = (tblListOfStudents.getModel().getValueAt(row,4).toString());
        bday = (tblListOfStudents.getModel().getValueAt(row,5).toString());
        age = (tblListOfStudents.getModel().getValueAt(row,6).toString());
        contactNumber = (tblListOfStudents.getModel().getValueAt(row,7).toString());
        emailAddress = (tblListOfStudents.getModel().getValueAt(row,8).toString());
        address = (tblListOfStudents.getModel().getValueAt(row,9).toString());
        
        txtStudentNumber.setText(studentNumber);
        txtLastName.setText(lastName);
        txtFirstName.setText(firstName);
        txtMiddleName.setText(middleName);
//        cboCourse.setSelectedItem(course);
        txtBday.setText(bday);
        txtAge.setText(age);
     //   txtContactNumber.setText(contactNumber);
        txtEmailAddress.setText(emailAddress);
      //  txtAddress.setText(address);
        
    }//GEN-LAST:event_tblListOfStudentsMouseClicked

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
    
    }//GEN-LAST:event_btnOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListOfStudents;
    private javax.swing.JTextField txtAge;
    private javax.swing.JFormattedTextField txtBday;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JFormattedTextField txtStudentNumber;
    // End of variables declaration//GEN-END:variables

    private void fillListView() {
        try{

            String  query = "SELECT * FROM `studenttbl`";
            statement = con.prepareStatement(query);
            result = statement.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)tblListOfStudents.getModel();
            tm.setRowCount(0);

            while(result.next()){
                Object o[] = {result.getString("studentNumber"),result.getString("lastName"),result.getString("firstName"),result.getString("middleName"),result.getString("course"),result.getString("birthday"),result.getString("age"),result.getString("contactNumber"),result.getString("emailAddress"),result.getString("address")};
                tm.addRow(o);
                }
            }
            catch(Exception e){

                JOptionPane.showMessageDialog(null,"Error in Employee Grid View..... "+e);
            }
    }
}